[workspace]
resolver = "2"
members = ["tokens"]
exclude = []

[workspace.dependencies]
substreams = "0.5"
substreams-solana = "0.13"
substreams-database-change = "1.3"
substreams-solana-program-instructions = "0.1"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
