services:
  clickhouse-sst:
    image: 'clickhouse/clickhouse-server:${CHVER:-latest}'
    user: '101:101'
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/config/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/config/clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'